# https://github.com/lukesampson/scoop-extras
- name: "Install extras bucket"
  scoop_bucket_install:
    state: present
    bucket: extras

- name: "Install extras tools"
  scoop_install:
    state: present
    bucket: extras
    name:
      - azure-cli
      - dnspy
      - everything
      - fiddler
      - fontbase
      - googlechrome
      - hack-font
      - ilspy
      - winmerge
      - linqpad
      - paint.net
      - powertoys
      - screentogif
      - slack
      - vscode
      - vswhere
      - windows-terminal
      - wiztree
